install:
	nmlc ezbase.nml -o $${HOME}/.local/share/openttd-jgrpp/newgrf/ezbase.grf

dry:
	nmlc ezbase.nml -o ezbase.grf >/dev/null

clean:
	nmlc ezbase.nml --clear-orphaned -R -o $${HOME}/.local/share/openttd-jgrpp/newgrf/ezbase.grf
